Issue 2840050: Use Dependency Injection for LocalStockService
BBGuy/commerce_stock pull request #8
Opened 2016-12-30 10:52 UTC by olafkarsten

Makes the LocalStockChecker and LocalStockUpdater a service an injects them in the LocalStockService. Adds test for the LocalStockService.

Needs the KernelTestBase from elsewhere. :smiley:

2017-01-04 16:46 UTC, BBGuy commented
Hi @olafkarsten looks like me pushing configuration injection https://github.com/BBGuy/commerce_stock/pull/5 broke this. Can you fix?

2017-01-05 01:19 UTC, steveoliver requested changes
Looks good -- just a few nitpicks.

2017-01-05 01:19 UTC, steveoliver commented on modules/local_storage/commerce_stock_local.services.yml
> +     alias: commerce_stock.local_stock_storage
Indent by 2, not 3.

2017-01-05 01:19 UTC, steveoliver commented on modules/local_storage/commerce_stock_local.services.yml
> +     class: Drupal\commerce_stock_local\LocalStockStorage
Indent these by 2, not 3.

2017-01-05 01:19 UTC, steveoliver commented on modules/local_storage/src/LocalStockService.php
> + */
Class docblock not needed.

2017-01-05 01:19 UTC, steveoliver commented on modules/local_storage/src/LocalStockService.php
> +   *    The stock updater.
Indentation.

2017-01-05 01:19 UTC, steveoliver commented on modules/local_storage/src/LocalStockService.php
> +   * LocalStockService constructor.
"Constructs a new LocalStockService object."

2017-01-05 01:19 UTC, steveoliver commented on modules/local_storage/src/LocalStockService.php
>      // Create the objects needed.
Can remove this comment

2017-01-05 01:19 UTC, steveoliver commented on tests/src/Kernel/CommerceStockKernelTestBase.php
> + */
Class docblock can be just one line: "Base class for Commerce Stock kernel tests."

2017-01-05 01:19 UTC, steveoliver commented on modules/local_storage/tests/src/Kernel/LocalStockServiceTest.php
> +    // Test that instation through container works.
spelling: instantiation

2017-01-05 01:19 UTC, steveoliver commented on modules/local_storage/tests/src/Kernel/LocalStockServiceTest.php
> + * Tests the LocalStockService.
"Tests the local stock service."

2017-01-05 01:19 UTC, steveoliver commented on modules/local_storage/src/LocalStockService.php
> +   *    The DI container.
Indentation.

2017-01-12 19:01 UTC, steveoliver commented
As I commented in https://www.drupal.org/node/2840050, let's use this PR to split LocalStockStorage into LocalStockChecker and LocalStockUpdater as well as the DI work you've already done.  Then we don't need the aliases.

2017-01-13 16:49 UTC, BBGuy commented
committed to gh and d.o https://www.drupal.org/commitlog/commit/21250/f5a447d7f0468fb144ca0bc25b49b051c6ce970b

2017-01-13 16:49 UTC, closed without merging